joonstargram/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
# from django.contrib.auth.models import User
from joonstargram.users.models import User
from joonstargram.posts.views import PostViewSet
from joonstargram.users.views import UserViewSet, HelloWorldAPI
from rest_framework import routers, serializers, viewsets

from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register('users', UserViewSet)
router.register('posts', PostViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path("api/", include("joonstargram.users.urls")),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    #login, registration등 path 설정
    path("api/rest-auth/", include("rest_auth.urls")),
    # 토큰 발급 및 재발급 페이지 설정
    path('api/rest-auth/obtain_token/', obtain_jwt_token, name="obtain-jwt"),
    path('api/rest-auth/refresh_token/', refresh_jwt_token, name="refresh-jwt"),
    path('api/hello', HelloWorldAPI.as_view()),
    path("api/rest-auth/registration/", include("rest_auth.registration.urls")),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    # path("", include("joonstargram.users.urls", namespace="users")),
    # /posts/
    path("posts/", include("joonstargram.posts.urls", namespace="posts")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

joonstargram/joonstargram/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('', views.index, name='index'),
    path('post_create/', views.post_create, name='post_create'),
    path('<int:post_id>/post_update', views.post_update, name='post_update'),
    path('<int:post_id>/post_delete', views.post_delete, name='post_delete'),
    path('<int:post_id>/comment_create', views.comment_create, name='comment_create'),
    path('<int:comment_id>/comment_delete', views.comment_delete, name='comment_delete'),
    path('<int:post_id>/post_image_like', views.post_image_like, name='post_image_like'),
    path('search/', views.search, name='search'),
    path('<int:user_id>/follow', views.follow, name='follow'),
    path('profile/', views.profile, name='profile'),
    path('<int:user_id>/profile/', views.other_profile, name='other_profile'),
    path('profile_update/', views.profile_update, name='profile_update'),
]

joonstargram/joonstargram/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("users/", views.CurrentUserAPIView.as_view(), name="current-user"),
    # path('', views.main, name='main'),
    path('signup/', views.signup, name='signup'),
    path('logout/' , views.logout, name='logout'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name="activate"),
]

joonstargram/joonstargram/posts/forms.py
from django import forms
from .models import *
from joonstargram.users.models import *

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["caption", "image"]

        labels = {
            "caption": "キャプション",
            "image": "写真",
        }

class UpdatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["caption"]

        labels = {
            "caption": "キャプション",
        }

class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea, label="")

    class Meta:
        model = Comment
        fields = ["content"]

class ProfileForm(forms.ModelForm):
    email = forms.EmailField(disabled=True, label='メールアドレス')
    name = forms.CharField(disabled=True, label='氏名')

    class Meta:
        model = User
        fields = [
            'email', 'name', 'username',
            'profile_photo', 'website',
            'intro', 'phone_number', 'gender',
            ]

        labels = {
            "username": "使用者名",
            "profile_photo": "写真",
            "website": "ウェブアドレス",
            "intro": "紹介",
            "phone_number": "電話番号",
            "gender": "性別",
        }

joonstargram/joonstargram/posts/views.py
from django.db.models.aggregates import Count
from django.shortcuts import redirect, render, get_object_or_404
from django.db.models import Q
from django.urls import reverse
from joonstargram.users.models import User
from rest_framework.permissions import AllowAny
from .models import *
from .serializers import *
from .forms import *

from rest_framework import serializers, viewsets

# Create your views here.
class PostViewSet(viewsets.ModelViewSet):
    permission_classes = (AllowAny,)
    queryset = Post.objects.all()
    serializer_class = PostSerializer

def index(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            comment_form = CommentForm()

            user = get_object_or_404(User, pk=request.user.id)
            followings = user.followings.all()
            posts = Post.objects.filter(
                Q(author__in=followings) | Q(author = user)
            ).order_by('-created')

            serializer = PostSerializer(posts, many=True)

            return render(request, 'posts/main.html',
                        {"posts": serializer.data, "comment_form": comment_form}
            )

def post_create(request):
    if request.method == 'GET':
        form = CreatePostForm()
        return render(request, 'posts/post_create.html', {"form": form})

    elif request.method == 'POST':
        if request.user.is_authenticated:
            user = get_object_or_404(User, pk=request.user.id)

            form = CreatePostForm(request.POST, request.FILES)
            if form.is_valid():
                # commit=False 데이터가 DB에 일단 저장 되지 않음.
                post = form.save(commit=False)

                post.author = user
                post.save()

            else:
                print(form.errors)


            return redirect(reverse('posts:index'))

        else:
            return render(request, 'users/main.html')

def post_update(request, post_id):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=post_id)

        if request.user != post.author:
            redirect(reverse('posts:index'))

        if request.method == 'GET':
            form = UpdatePostForm(instance=post)
            return render(request, 'posts/post_update.html',
                        {"form": form, "post": post}
            )

        elif request.method == 'POST':
            form = UpdatePostForm(request.POST, instance=post)
            if form.is_valid():
                post.caption = form.cleaned_data['caption']
                post.save()

            return redirect(reverse('posts:index'))

    else:
        return render(request, 'users/main.html')

def post_delete(request, post_id):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=post_id)

        if request.user == post.author:
            post.delete()

        return redirect(reverse('posts:index'))

    else:
        return render(request, 'users/main.html')

def post_image_like(request, post_id):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=post_id)

        if request.user in post.image_likes.all():
            post.image_likes.remove(request.user)
        else:
            post.image_likes.add(request.user)

        return redirect(reverse('posts:index'))

    else:
        return render(request, 'users/main.html')

def comment_create(request, post_id):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=post_id)

        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.posts = post
            comment.save()

            return redirect(reverse('posts:index'))

        else:
            return render(request, 'users/main.html')

def comment_delete(request, comment_id):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_id)

        if request.user == comment.author:
            comment.delete()

        return redirect(reverse('posts:index'))

    else:
        return render(request, 'users/main.html')

def search(request):
    if request.user.is_authenticated:
        users = User.objects.all().exclude(pk=request.user.id)
        keyword = request.GET.get('keyword', '')

        if keyword:
            users = users.filter(username__icontains=keyword)

        serializer = PostAuthorSerializer(users, many=True)

        return render(request, 'posts/search.html',
                    {'users': serializer.data, 'keyword': keyword})

    else:
        return render(request, 'users/main.html')

def follow(request, user_id):
    if request.user.is_authenticated:
        user = get_object_or_404(User, id=user_id)

        if request.user in user.followers.all():
            user.followers.remove(request.user)
            request.user.followings.remove(user)

        else:
            user.followers.add(request.user)
            request.user.followings.add(user)

        return redirect(reverse('posts:search'))

    else:
        return render(request, 'users/main.html')

def profile(request):
    if request.user.is_authenticated:
        user = get_object_or_404(User, pk=request.user.id)

        posts = Post.objects.filter(
                Q(author = user)
            ).order_by('-created')

        serializer = PostSerializer(posts, many=True)

        return render(request, 'posts/profile.html', {'user': user, 'posts': serializer.data})

    else:
        return render(request, 'users/main.html')

def other_profile(request, user_id):
    if request.user.is_authenticated:
        user = get_object_or_404(User, pk=user_id)

        posts = Post.objects.filter(
                Q(author = user)
            ).order_by('-created')

        serializer = PostSerializer(posts, many=True)

        return render(request, 'posts/other_profile.html', {'user': user, 'posts': serializer.data})

    else:
        return render(request, 'users/main.html')

def profile_update(request):
    if request.user.is_authenticated:
        user = get_object_or_404(User, pk=request.user.id)

        if request.method == 'GET':
            form = ProfileForm(instance=user)
            return render(request, 'posts/profile_update.html',
                        {"form": form, "user": user}
            )

        elif request.method == 'POST':
            form = ProfileForm(request.POST, request.FILES, instance=user)

            if form.is_valid():
                user.username = form.cleaned_data['username']
                user.profile_photo = form.cleaned_data['profile_photo']
                user.website = form.cleaned_data['website']
                user.intro = form.cleaned_data['intro']
                user.phone_number = form.cleaned_data['phone_number']
                user.gender = form.cleaned_data['gender']
                user.save()
            else:
                print(form.errors)

            return redirect(reverse('posts:profile'))

joonstargram/joonstargram/users/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sites.models import Site
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from .forms import SignUpForm
from .models import User


from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage, send_mail
from .tokens import account_activation_token
from django.utils.encoding import force_bytes, force_text

from rest_framework import viewsets
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import UserSerializer

# ViewSets define the view behavior.
class HelloWorldAPI(GenericAPIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request, format=None):
        return Response(data={"greeting": "Hello World"}, status=status.HTTP_200_OK)

class UserViewSet(viewsets.ModelViewSet):
    permission_classes = (IsAuthenticated,)

    queryset = User.objects.all()
    serializer_class = UserSerializer

class CurrentUserAPIView(APIView):

    def get(self, request):
        serializer = UserSerializer(request.user)
        return Response(serializer.data)

def main(request):
    if request.method == 'GET':
        return render(request, 'users/main.html')

    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return HttpResponseRedirect(reverse('posts:index'))
        else:
            # Return an 'invalid login' error message.
            return render(request, 'users/main.html')

def signup(request):
    if request.method == 'GET':
        form = SignUpForm()

        return render(request, 'users/signup.html', {'form': form})

    elif request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data['username']
            # password = form.cleaned_data['password']
            email = form.cleaned_data['email']

            user = User.objects.get(username=username)
            current_site = get_current_site(request)

            message = render_to_string('users/activation_email.html',
                {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
                }
            )

            mail_title = "【Joonstargram】アカウント認証確認"
            mail_to = user.email
            email = EmailMessage(mail_title, message, to=[mail_to])
            email.send()

            return HttpResponseRedirect(reverse('users:main'))


            # if user is not None:
            #     login(request, user)
            #     # Redirect to a success page.
            #     return HttpResponseRedirect(reverse('posts:index'))

        return render(request, 'users/main.html')

def logout(request):
    request.session.flush()

    return render(request, 'users/main.html')

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExsit):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        return HttpResponseRedirect(reverse("posts:index"))
    else:
        return render(request, 'users/main.html', {'error' : '계정 활성화 오류'})

joonstargram/joonstargram/templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}Joonstargram</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "css/posts/base.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/posts/main.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/posts/header.css" %}">
    <script src="https://kit.fontawesome.com/936b672cea.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>

    <div class="header">
      {% include "posts/header.html" %}
    </div>

    <div>
      {% block content %}
      {% endblock %}
    </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous">


  </script>
  </body>
</html>

joonstargram/joonstargram/templates/posts/header.html
{% load static %}
{% load bootstrap5 %}

<header>

  <div class="header-box">
    <div class="logo-img">
      <a href="{% url 'posts:index' %}">
        <img src="{% static "images/posts/logo.png" %}" alt="logo" />
      </a>
    </div>

    <div class="search-box">
      <form method="get" action="{% url 'posts:search' %}" enctype="multipart/form-data">
        <input type="text" name="keyword" value="{{ keyword }}" placeholder="Search" />
      </form>
    </div>

    <div class="header-right">
      <div>
        <a href="{% url 'posts:index' %}">
          <i class="fas fa-home fa-2x"></i>
        </a>
      </div>
      <div>
        <a href="{% url 'posts:post_create' %}">
          <i class="fas fa-plus-circle fa-2x"></i>
        </a>
      </div>
      <div class="dropdown">
        <a  href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fas fa-user fa-2x"></i>
        </a>

        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <li><a class="dropdown-item" href="{% url 'posts:profile' %}">Profile</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
        </ul>
      </div>
    </div>
  </div>

</header>

joonstargram/joonstargram/templates/posts/main.html
{% extends "posts/base.html" %} {% load static %} {% block content %} {% for
post in posts %}
<div class="post-box">
  <div class="post-header">
    <div class="profile">
      {% if post.author.profile_photo != None %}
      <img src="{{ post.author.profile_photo}}" />
      {% else %} <img src="{% static "images/posts/default_profile.png" %}"> {%
      endif %}
      <div>{{ post.author.username }}</div>
    </div>

    {% if user.id == post.author.id %}
    <div class="icon">
      <a href="{% url 'posts:post_update' post.id %}">
        <i class="fas fa-pencil-alt fa-lg"></i>
      </a>
      <a href="{% url 'posts:post_delete' post.id %}">
        <i class="fas fa-trash-alt fa-lg"></i>
      </a>
    </div>
    {% endif %}
  </div>

  <img class="post-image" src="{{ post.image }}" />

  <div class="like-icon">
    <a href="{% url 'posts:post_image_like' post.id %}">
      {% if user.id in post.image_likes %}
      <i class="fas fa-heart fa-2x" style="color: red"></i>
      {% else %}
      <i class="far fa-heart fa-2x"></i>
      {% endif %}
    </a>
    {{ post.image_likes | length }} likes
  </div>

  <div class="desc-box">
    <div class="caption">
      <b>{{ post.author.username }}</b>
      {{ post.caption }}
    </div>

    <div class="comment">
      {% for comment in post.comment_post %}
      <div>
        <b>{{ comment.author.username }}</b>
        {{ comment.content }} {% if user.id == comment.author.id %}
        <a href="{% url 'posts:comment_delete' comment.id %}">
          <i class="fas fa-trash-alt" style="color: #0095f6"></i>
        </a>
        {% endif %}
      </div>
      {% endfor %}
    </div>
  </div>

  <div class="comment-input">
    <form method="post" action="{% url 'posts:comment_create' post.id %}">
      {% csrf_token %} {{ comment_form }}
      <input type="submit" value="作成" />
    </form>
  </div>
</div>
{% endfor %} {% endblock %}

joonstargram/joonstargram/templates/posts/other_profile.html
{% extends "posts/base.html" %}
{% load static %}

{% block title %}
{{ user.username }} Profile
{% endblock %}

{% block content %}

<div class="profile-box">

  <div class="profile-img">
    <img src={% if user.profile_photo %}"{{ user.profile_photo.url }}"
              {% else %}"{% static "images/posts/default_profile.png" %}"
              {% endif %}
              >
  </div>

  <div class="profile-main">
    <div class="profile-header">
      <h2>{{ user.username }}</h2>
    </div>

    <ul class="counts">
      <li>ポスト <b>0</b></li>
      <li>フォロワー <b>{{ user.followers.count }}</b></li>
      <li>フォロー <b>{{ user.followings.count }}</b></li>
    </ul>

    <div class="profile">
      <h3>{{ user.name }}</h3><br />
      {% if user.intro != None %}
      <span>{{ user.intro }}</span>
      {% endif %}
    </div>
  </div>

</div>

<div class="thumnail-box">

  <div class="thumnail-header">
    <h2>ポスト</h2>
  </div>

  {% if posts %}
  <div class="thumnail-main">
      {% for post in posts %}
        <img src="{{ post.image }}">
      {% endfor %}
  </div>
  {% endif %}

</div>

{% endblock %}

joonstargram/joonstargram/templates/posts/post_create.html
{% extends "posts/base.html" %}

{% block title %}
Create Post
{% endblock %}

{% block content %}
<div class="post-edit">
  <div class="create">

    <h1>Create Post</h1>

    <div class="post-form">
      <form method="post" action="{% url 'posts:post_create' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
      </form>
    </div>

  </div>

</div>

{% endblock %}

joonstargram/joonstargram/templates/posts/post_update.html
{% extends "posts/base.html" %}

{% block title %}
Update Post
{% endblock %}

{% block content %}
<div class="post-edit">
  <div class="create">


      <h1>Update Post</h1>


    <div class="form">
      <form method="post" action="{% url 'posts:post_update' post.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
      </form>
    </div>

  </div>
</div>
{% endblock %}

joonstargram/joonstargram/templates/posts/profile.html
{% extends "posts/base.html" %}
{% load static %}

{% block title %}
My Profile
{% endblock %}

{% block content %}

<div class="profile-box">

  <div class="profile-img">
    <img src={% if user.profile_photo %}"{{ user.profile_photo.url }}"
              {% else %}"{% static "images/posts/default_profile.png" %}"
              {% endif %}
              >
  </div>

  <div class="profile-main">
    <div class="profile-header">
      <h2>{{ user.username }}</h2>
      <a href="{% url 'posts:profile_update' %}" enctype="multipart/form-data">
        <i class="fas fa-cog fa-lg"></i>
      </a>
    </div>

    <ul class="counts">
      <li>ポスト <b>{{ posts | length }}</b></li>
      <li>フォロワー <b>{{ user.followers.count }}</b></li>
      <li>フォロー <b>{{ user.followings.count }}</b></li>
    </ul>

    <div class="profile">
      <h3>{{ user.name }}</h3><br />
      {% if user.intro != None %}
      <span>{{ user.intro }}</span>
      {% endif %}
    </div>
  </div>

</div>

<div class="thumnail-box">

  <div class="thumnail-header">
    <h2>ポスト</h2>
  </div>

  {% if posts %}
  <div class="thumnail-main">
      {% for post in posts %}
        <img src="{{ post.image }}">
      {% endfor %}
  </div>
  {% endif %}

</div>

{% endblock %}

joonstargram/joonstargram/templates/posts/profile_update.html
{% extends "posts/base.html" %}

{% block title %}
Update Profile
{% endblock %}

{% block content %}
<div class="post-edit">
  <div class="create">


      <h1>Update Profile</h1>


    <div class="form">
      <form method="post" action="{% url 'posts:profile_update' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
      </form>
    </div>

  </div>
</div>

{% endblock %}

joonstargram/joonstargram/templates/posts/search.html
{% extends "posts/base.html" %}
{% load static %}

{% block title %}
User Search
{% endblock %}

{% block content %}


{% for user in users %}
  <div class="search-result-box">
    <div class="profile-image">
    {% if user.profile_photo != None %}
      <img src="{{ user.profile_photo}}">
    {% else %}
      <img src="{% static "images/posts/default_profile.png" %}">
    {% endif %}
    </div>

    <div class="profile-main">
      <a href="{% url "posts:other_profile" user.id %}">
        <b>{{ user.username }}</b>
      </a>
      <br /><br />
      {% if user.intro %}
        {{ user.intro }}
      {% endif %}
    </div>

    <div class="icon-follow">
      <a href="{% url "posts:follow" user.id %}">
      {% if request.user.id in user.followers %}
        <i class="fas fa-user-check fa-2x"></i>
      {% else %}
        <i class="fas fa-user fa-2x"></i>
      {% endif %}
      </a>
    </div>

  </div>
{% endfor %}

{% endblock %}